import type { AliplayerOptions, AliplayerV2Props, VueAliplayerV2Expose } from './types';
declare const __VLS_export: import("vue").DefineComponent<AliplayerV2Props, VueAliplayerV2Expose, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {} & {
    canplay: (payload?: unknown) => any;
    ended: (payload?: unknown) => any;
    error: (payload?: unknown) => any;
    pause: (payload?: unknown) => any;
    play: (payload?: unknown) => any;
    playing: (payload?: unknown) => any;
    timeupdate: (payload?: unknown) => any;
    waiting: (payload?: unknown) => any;
    ready: (payload?: unknown) => any;
    liveStreamStop: (payload?: unknown) => any;
    onM3u8Retry: (payload?: unknown) => any;
    hideBar: (payload?: unknown) => any;
    showBar: (payload?: unknown) => any;
    snapshoted: (payload?: unknown) => any;
    requestFullScreen: (payload?: unknown) => any;
    cancelFullScreen: (payload?: unknown) => any;
    startSeek: (payload?: unknown) => any;
    completeSeek: (payload?: unknown) => any;
    "sdk-error": (error: Error) => any;
}, string, import("vue").PublicProps, Readonly<AliplayerV2Props> & Readonly<{
    onCanplay?: ((payload?: unknown) => any) | undefined;
    onEnded?: ((payload?: unknown) => any) | undefined;
    onError?: ((payload?: unknown) => any) | undefined;
    onPause?: ((payload?: unknown) => any) | undefined;
    onPlay?: ((payload?: unknown) => any) | undefined;
    onPlaying?: ((payload?: unknown) => any) | undefined;
    onTimeupdate?: ((payload?: unknown) => any) | undefined;
    onWaiting?: ((payload?: unknown) => any) | undefined;
    onReady?: ((payload?: unknown) => any) | undefined;
    onLiveStreamStop?: ((payload?: unknown) => any) | undefined;
    onOnM3u8Retry?: ((payload?: unknown) => any) | undefined;
    onHideBar?: ((payload?: unknown) => any) | undefined;
    onShowBar?: ((payload?: unknown) => any) | undefined;
    onSnapshoted?: ((payload?: unknown) => any) | undefined;
    onRequestFullScreen?: ((payload?: unknown) => any) | undefined;
    onCancelFullScreen?: ((payload?: unknown) => any) | undefined;
    onStartSeek?: ((payload?: unknown) => any) | undefined;
    onCompleteSeek?: ((payload?: unknown) => any) | undefined;
    "onSdk-error"?: ((error: Error) => any) | undefined;
}>, {
    source: string | null;
    autoFormat: boolean;
    forbidFastForward: boolean;
    license: import("./types").AliplayerLicense | null;
    lowLatency: boolean;
    normalizeSourceUrl: boolean;
    options: AliplayerOptions | null;
    sdkVersion: string;
    cssLink: string;
    scriptSrc: string;
    componentScripts: string[];
    disableTracking: boolean;
    trackingUrlPatterns: Array<string | RegExp>;
}, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
declare const _default: typeof __VLS_export;
export default _default;
//# sourceMappingURL=index.vue.d.ts.map